# Generated by Django 5.0.3 on 2024-03-18 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='api.category'),
        ),
        migrations.AlterField(
            model_name='component',
            name='parametrs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametr', to='api.parametrs'),
        ),
        migrations.AlterField(
            model_name='component',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to=settings.AUTH_USER_MODEL),
        ),
    ]
